# Generated by Django 4.2.19 on 2025-04-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_expense_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor'),
        ),
    ]
